;Branch if less than or equal to 0. 
;Opcode: 003400

START: 
	mov #5, R1 ;R1 = 5
    sub R1, #4
    BLE L1	;Shouldn't work

	SUB R1, #1
    BLE L2	;Should work

	BR L4 	;Fallthru, Should never run!. Opcode:000400
    HALT

L1:
	mov #1, R1
    HALT
L2:
	mov #2, R1
    SUB R1, #3
    BLE L3	;should work
    HALT

L3:
    mov #3, R1
    HALT

L4:
    mov #4, R1
    HALT

.END START
