;Branch Minus
;branch if minus. Opcode: 100400

START: 
	mov #5, R1 ;R1 = 5
	sub R1, #5 ;R1 = 0
    BMI L1	;testing 0

	ADD R1, #5 ;R1 = 5
    BMI L2	;testing positive

    SUB R1, #6 ;R1 = -1
    BMI L3	;testing negative
    
	BR L4 	;Fallthru, Should never run!. Opcode:000400
    HALT

L1:
	mov #1, R1
    HALT
L2:
	mov #2, R1
    HALT

L3:
    mov #3, R1
    HALT

L4:
    mov #4, R1
    HALT

.END START
