;Branch Plus
;branch if plus. N = 0. Opcode: 100000

START: 
	mov #5, R1 ;R1 = 5
	sub #5, R1 ;R1 = 0
    BPL L1	;testing 0

	sub #5, R1 ;R1 = -5
    BPL L2	;testing negative

    add #6, R1 ;R1 = 1
    BPL L3	;testing positive
    
	BR L4 	;Fallthru, Should never run!. Opcode:000400
    HALT

L1:
	mov #1, R1
    HALT
L2:
	mov #2, R1
    HALT

L3:
    mov #3, R1
    HALT

L4:
    mov #4, R1
    HALT

.END START
