;Branch Overflow clear (AKA branch if 
;branch if overflow is clear. v = 0. Opcode: 102000

A: .WORD 077776

START: 
	mov A, R1 ;R1 = 077777
	ADD R1, #1 ;R1 = 100000. Overflowed!
    BVC L1	;Shouldn't work

	ADD R1, #1 ;R1 = 100001. Shouldnt cause overflow
    BVC L2	;Should work
    
	BR L3 	;Fallthru, Should never run!. Opcode:000400
    HALT

L1:
	mov #1, R1
    HALT
L2:
	mov #2, R1
    HALT

L3:
    mov #3, R1
    HALT


.END START
