;Branch Overflow Set 
;branch if overflow is Set. v = 1. Opcode: 102400
A: .WORD 077776

START: 
	mov A, R1 ;R1 = 077776
	ADD R1, #1 ;R1 = 077776. Shouldn't cause overflow
    BVS L1	;Shouldn't work

	ADD R1, #1 ;R1 = 100000. Overflowed!
    BVS L2	;Should work
    
	BR L3 	;Fallthru, Should never run!. Opcode:000400
    HALT

L1:
	mov #1, R1
    HALT
L2:
	mov #2, R1
    HALT

L3:
    mov #3, R1
    HALT


.END START
